# TCL File Generated by Component Editor 17.1
# Tue Dec 25 11:58:07 CET 2018
# DO NOT MODIFY


# 
# videosampler "videosampler" v4.0
# LMag 2018.12.25.11:58:07
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module videosampler
# 
set_module_property DESCRIPTION ""
set_module_property NAME videosampler
set_module_property VERSION 4.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP CameraOneFrame
set_module_property AUTHOR LMag
set_module_property DISPLAY_NAME videosampler
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL videosampler
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file videosampler.v VERILOG PATH hdl/videosampler.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter DATA_WIDTH INTEGER 32
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter PIXEL_WIDTH INTEGER 8
set_parameter_property PIXEL_WIDTH DEFAULT_VALUE 8
set_parameter_property PIXEL_WIDTH DISPLAY_NAME PIXEL_WIDTH
set_parameter_property PIXEL_WIDTH TYPE INTEGER
set_parameter_property PIXEL_WIDTH UNITS None
set_parameter_property PIXEL_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PIXEL_WIDTH HDL_PARAMETER true
add_parameter FIFO_DEPTH INTEGER 2048
set_parameter_property FIFO_DEPTH DEFAULT_VALUE 2048
set_parameter_property FIFO_DEPTH DISPLAY_NAME FIFO_DEPTH
set_parameter_property FIFO_DEPTH TYPE INTEGER
set_parameter_property FIFO_DEPTH UNITS None
set_parameter_property FIFO_DEPTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FIFO_DEPTH HDL_PARAMETER true
add_parameter DEFAULT_SCR INTEGER 0
set_parameter_property DEFAULT_SCR DEFAULT_VALUE 0
set_parameter_property DEFAULT_SCR DISPLAY_NAME DEFAULT_SCR
set_parameter_property DEFAULT_SCR TYPE INTEGER
set_parameter_property DEFAULT_SCR UNITS None
set_parameter_property DEFAULT_SCR ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DEFAULT_SCR HDL_PARAMETER true
add_parameter DEFAULT_FLOWLENGTH INTEGER 262144
set_parameter_property DEFAULT_FLOWLENGTH DEFAULT_VALUE 262144
set_parameter_property DEFAULT_FLOWLENGTH DISPLAY_NAME DEFAULT_FLOWLENGTH
set_parameter_property DEFAULT_FLOWLENGTH TYPE INTEGER
set_parameter_property DEFAULT_FLOWLENGTH UNITS None
set_parameter_property DEFAULT_FLOWLENGTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DEFAULT_FLOWLENGTH HDL_PARAMETER true
add_parameter HREF_POLARITY STRING high
set_parameter_property HREF_POLARITY DEFAULT_VALUE high
set_parameter_property HREF_POLARITY DISPLAY_NAME HREF_POLARITY
set_parameter_property HREF_POLARITY TYPE STRING
set_parameter_property HREF_POLARITY UNITS None
set_parameter_property HREF_POLARITY HDL_PARAMETER true
add_parameter VSYNC_POLARITY STRING high
set_parameter_property VSYNC_POLARITY DEFAULT_VALUE high
set_parameter_property VSYNC_POLARITY DISPLAY_NAME VSYNC_POLARITY
set_parameter_property VSYNC_POLARITY TYPE STRING
set_parameter_property VSYNC_POLARITY UNITS None
set_parameter_property VSYNC_POLARITY HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 addr_rel_i address Input 3
add_interface_port avalon_slave_0 wr_i write Input 1
add_interface_port avalon_slave_0 datawr_i writedata Input 32
add_interface_port avalon_slave_0 rd_i read Input 1
add_interface_port avalon_slave_0 datard_o readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk_i clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset_n_i reset_n Input 1


# 
# connection point pixel_i
# 
add_interface pixel_i conduit end
set_interface_property pixel_i associatedClock clock_sink
set_interface_property pixel_i associatedReset ""
set_interface_property pixel_i ENABLED true
set_interface_property pixel_i EXPORT_OF ""
set_interface_property pixel_i PORT_NAME_MAP ""
set_interface_property pixel_i CMSIS_SVD_VARIABLES ""
set_interface_property pixel_i SVD_ADDRESS_GROUP ""

add_interface_port pixel_i pixel_i conduit Input 8


# 
# connection point vsync_i
# 
add_interface vsync_i conduit end
set_interface_property vsync_i associatedClock clock_sink
set_interface_property vsync_i associatedReset ""
set_interface_property vsync_i ENABLED true
set_interface_property vsync_i EXPORT_OF ""
set_interface_property vsync_i PORT_NAME_MAP ""
set_interface_property vsync_i CMSIS_SVD_VARIABLES ""
set_interface_property vsync_i SVD_ADDRESS_GROUP ""

add_interface_port vsync_i vsync_i conduit Input 1


# 
# connection point pclk_i
# 
add_interface pclk_i conduit end
set_interface_property pclk_i associatedClock clock_sink
set_interface_property pclk_i associatedReset ""
set_interface_property pclk_i ENABLED true
set_interface_property pclk_i EXPORT_OF ""
set_interface_property pclk_i PORT_NAME_MAP ""
set_interface_property pclk_i CMSIS_SVD_VARIABLES ""
set_interface_property pclk_i SVD_ADDRESS_GROUP ""

add_interface_port pclk_i pclk_i conduit Input 1


# 
# connection point href
# 
add_interface href conduit end
set_interface_property href associatedClock clock_sink
set_interface_property href associatedReset ""
set_interface_property href ENABLED true
set_interface_property href EXPORT_OF ""
set_interface_property href PORT_NAME_MAP ""
set_interface_property href CMSIS_SVD_VARIABLES ""
set_interface_property href SVD_ADDRESS_GROUP ""

add_interface_port href href_i conduit Input 1


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock_sink
set_interface_property avalon_streaming_source associatedReset reset_sink
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source out_data data Output 8
add_interface_port avalon_streaming_source out_dv valid Output 1
add_interface_port avalon_streaming_source out_eop endofpacket Output 1
add_interface_port avalon_streaming_source out_sop startofpacket Output 1

